### ISSUE TITLE
[BUG] Build fails with missing dependency `build-tools`

### ISSUE THREAD

**Issue by faxm0dem** [opensearch-project/sql#154]
```
☠ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'opensearch-sql'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.opensearch.gradle:build-tools:1.0.0-rc1.
     Searched in the following locations:
       - file:/home/me/.m2/repository/org/opensearch/gradle/build-tools/1.0.0-rc1/build-tools-1.0.0-rc1.pom
       - https://repo.maven.apache.org/maven2/org/opensearch/gradle/build-tools/1.0.0-rc1/build-tools-1.0.0-rc1.pom
       - https://jcenter.bintray.com/org/opensearch/gradle/build-tools/1.0.0-rc1/build-tools-1.0.0-rc1.pom
       - https://plugins.gradle.org/m2/org/opensearch/gradle/build-tools/1.0.0-rc1/build-tools-1.0.0-rc1.pom
     Required by:
         project :
```

**Comment by chloe-zh** [comment]
Hi @faxm0dem the build failure is because the opensearch dependencies (v1.0.0-rc) were not available in the maven repository yet since the GA was not officially released until this Monday. The good thing is we just released v1.0.0.0. Please checkout the latest source code and try to build against v1.0.0.0, this should work fine.

**Comment by faxm0dem** [comment]
Thanks. I tried, but I still get the same error. I see there are many tags that resemble 1.0.0.0 maybe I checked out the wrong one ?

# tag 1.0.0.0

```
> git status
HEAD detached at 1.0.0.0
nothing to commit, working tree clean
> ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'opensearch-sql'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.opensearch.gradle:build-tools:1.0.0.
     Searched in the following locations:
       - file:/home/fwernli/.m2/repository/org/opensearch/gradle/build-tools/1.0.0/build-tools-1.0.0.pom
       - https://repo.maven.apache.org/maven2/org/opensearch/gradle/build-tools/1.0.0/build-tools-1.0.0.pom
       - https://jcenter.bintray.com/org/opensearch/gradle/build-tools/1.0.0/build-tools-1.0.0.pom
       - https://plugins.gradle.org/m2/org/opensearch/gradle/build-tools/1.0.0/build-tools-1.0.0.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

# tag v1.0.0.0

```
> git status
HEAD detached at v1.0.0.0
nothing to commit, working tree clean
> ./gradlew build

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/tmp/sql/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'opendistro-sql'.
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > JAVA_HOME must be set to build Elasticsearch. Note that if the variable was just set you might have to run `./gradlew --stop` for it to be picked up. See https://github.com/elastic/elasticsearch/issues/31399 details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'opendistro-sql'.
> Must specify license and notice file for project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by hashworks** [comment]
@chloe-zh This is still an issue with all plugins. Do you plan to release `org.opensearch.gradle:build-tools` in Maven Central? If not, how would one provide it in a local repository?

**Comment by dblock** [comment]
> @chloe-zh This is still an issue with all plugins. Do you plan to release `org.opensearch.gradle:build-tools` in Maven Central? If not, how would one provide it in a local repository?

Yes, https://github.com/opensearch-project/opensearch-build/issues/20.

**Comment by dblock** [comment]
@faxm0dem For now, follow the sequence in https://github.com/opensearch-project/sql/blob/main/.github/workflows/sql-test-and-build-workflow.yml#L26 and https://github.com/opensearch-project/opensearch-plugins#building-plugins-with-opensearch

**Comment by dai-chen** [comment]
Closing this for now. Feel free to reopen if you need anything. Thanks!
