### ISSUE TITLE
[BUG] timestampdiff return wrong schema in V2

### ISSUE THREAD

**Issue by xinyual** [opensearch-project/sql#3475]
**What is the bug?**
The wrong schema we use for function timestampdiff.

**How can one reproduce the bug?**
Create any index. Then run ppl: `source=demo | eval f = timestampdiff(YEAR, '1997-01-01 00:00:00', '2001-03-06 00:00:00') | fields f `
Then it returns 
```
{
    "schema": [
        {
            "name": "f",
            "type": "timestamp"
        }
    ],
    "datarows": [
        [
            4
        ]
    ],
    "total": 1,
    "size": 1
}
```

**What is the expected behavior?**
The schema should not be timestamp. Int or long could be better.

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by LantaoJin** [comment]
With Calcite, the schema of `timestampdiff ` will return `integer`. Mark it a breaking.

**Comment by LantaoJin** [comment]
Resolved by #3473

**Comment by qianheng-aws** [comment]
`CalciteDateTimeFunctionIT::testTimestampDiff ` still failed caused by wrong schema
